In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("willianoliveiragibin/food-delivery-time")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/willianoliveiragibin/food-delivery-time?dataset_version_number=1...

100%|██████████| 288k/288k [00:00<00:00, 64.0MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/willianoliveiragibin/food-delivery-time/versions/1

Cleaning the data

---

Working on with the Traffic level column

In [ ]:
import pandas as pd

df = pd.read_csv("/content/Food_Time new.csv")

Check all unique values in the column

In [ ]:
df["Traffic_Level"].unique()

array(['High', 'Low', 'Moderate', nan, 'Very High', 'Very Low'],
      dtype=object)

Remove extra spaces (sometimes values contain hidden spaces)

In [ ]:
df["Traffic_Level"] = df["Traffic_Level"].str.strip()

Standardize the text format
(This avoids issues like low, LOW, Low.)

In [ ]:
df["Traffic_Level"] = df["Traffic_Level"].str.title()

Seeing full distribution of values in this traffic column and then replacing the N/A values to missing values.

In [ ]:
df["Traffic_Level"].value_counts(dropna=False)

Traffic_Level
High         2736
Moderate     2219
Very High    1772
Low          1726
NaN           915
Very Low      632
Name: count, dtype: int64

In [ ]:
df["Traffic_Level"] = df["Traffic_Level"].replace("N/A", pd.NA)

Checking the id column

In [ ]:
df["ID"].duplicated().sum()

np.int64(5)

In [ ]:
df[df["ID"].duplicated()]

,Traffic_Level,ID,Delivery_person_ID,weather_description,Type_of_order,Type_of_vehicle,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,temperature,humidity,precipitation,Distance (km),TARGET
4922,Moderate,9.00E+02,INDORES14DEL03,haze,Snack,motorcycle,28,4.0,22.761.593,75.886.362,22.821.593,75.946.362,17.14,72.0,0.0,11.75,3.136.666.667
7217,NaN,BEFÂ 1.00,AGRRES13DEL02,clear sky,Drinks,scooter,50,6.0,-27.159.795,-7.804.299,27.209.795,7.809.299,25.96,37.0,0.0,NaN,#VALUE!
7253,NaN,5.00E+09,BANGRES18DEL01,haze,Snack,motorcycle,29,4.6,-12.913.041,77.683.237,12.983.041,77.753.237,23.09,73.0,0.0,NaN,#VALUE!
9151,Very High,6.00E+03,PUNERES13DEL02,clear sky,Snack,motorcycle,36,4.6,1.856.245,73.916.619,1.869.245,74.046.619,23.60,46.0,0.0,29.32,70.2
9855,Very Low,6.00E+02,MUMRES01DEL01,smoke,Snack,scooter,22,4.8,1.912.663,72.829.976,1.913.663,72.839.976,27.92,57.0,0.0,2.05,1.968.333.333

In [ ]:
df["ID"].isna().sum()

np.int64(0)

Checking if Delivery_person_id has missing values

In [ ]:
df["Delivery_person_ID"].isna().sum()

np.int64(0)

Weather_description

In [ ]:
df["weather_description"].unique()

array(['mist', 'clear sky', 'overcast clouds', 'broken clouds', 'haze',
       'scattered clouds', 'fog', 'smoke', 'few clouds', nan,
       'light rain', 'moderate rain'], dtype=object)

In [ ]:
df["weather_description"].value_counts()

weather_description
clear sky           3260
haze                2406
mist                1751
broken clouds        721
light rain           536
smoke                501
scattered clouds     422
overcast clouds      308
fog                   49
few clouds            40
moderate rain          1
Name: count, dtype: int64

In [ ]:
df["weather_description"].isna().sum()

np.int64(5)

In [ ]:
df["weather_description"].str.lower().unique()

array(['mist', 'clear sky', 'overcast clouds', 'broken clouds', 'haze',
       'scattered clouds', 'fog', 'smoke', 'few clouds', nan,
       'light rain', 'moderate rain'], dtype=object)

In [ ]:
df["weather_description"].str.strip().equals(df["weather_description"])

True

Type of order

In [ ]:
df["Type_of_order"].isna().sum()

np.int64(0)

In [ ]:
df["Type_of_order"].unique()

array(['Snack', 'Meal', 'Drinks', 'Buffet'], dtype=object)

In [ ]:
df["Type_of_order"].value_counts()

Type_of_order
Snack     2551
Meal      2530
Drinks    2507
Buffet    2412
Name: count, dtype: int64

In [ ]:
df["Type_of_order"].str.lower().unique()

array(['snack', 'meal', 'drinks', 'buffet'], dtype=object)

In [ ]:
df["Type_of_order"].str.strip().equals(df["Type_of_order"])

True

Type of vehicle

In [ ]:
df["Type_of_vehicle"].isna().sum()

np.int64(0)

In [ ]:
df["Type_of_vehicle"].unique()

array(['scooter', 'motorcycle', 'electric_scooter', 'bicycle'],
      dtype=object)

In [ ]:
df["Type_of_vehicle"].value_counts()

Type_of_vehicle
motorcycle          5862
scooter             3304
electric_scooter     814
bicycle               20
Name: count, dtype: int64

In [ ]:
df["Type_of_vehicle"].str.lower().unique()

array(['scooter', 'motorcycle', 'electric_scooter', 'bicycle'],
      dtype=object)

In [ ]:
df["Type_of_vehicle"].str.strip().equals(df["Type_of_vehicle"])

True

Delivery Person Age

In [ ]:
df["Delivery_person_Age"].isna().sum()

np.int64(0)

In [ ]:
df["Delivery_person_Age"].dtype

dtype('int64')

In [ ]:
df["Delivery_person_Age"].min()

15

In [ ]:
df["Delivery_person_Age"].max()

50

In [ ]:
df["Delivery_person_Age"].describe()

count    10000.000000
mean        29.522000
std          5.700348
min         15.000000
25%         25.000000
50%         29.000000
75%         34.000000
max         50.000000
Name: Delivery_person_Age, dtype: float64

In [ ]:
df["Delivery_person_Age"].value_counts()

Delivery_person_Age
29    889
38    515
37    508
21    506
35    504
27    493
25    491
36    488
24    487
22    482
31    477
33    476
34    474
28    473
30    471
20    471
32    461
26    444
23    440
39    435
50     10
15      5
Name: count, dtype: int64

Delivery Person Rating

In [ ]:
df["Delivery_person_Ratings"].unique()

array([4.6, 4.7, 4.2, 4.9, 4. , 4.3, 4.8, 4.4, 5. , 3.9, 4.1, 4.5, 3.8,
       2.6, 3.5, 3.7, 2.5, 3.6, 3.1, 2.7, 3.3, 3.4, 2.9, 3.2, 1. , 6. ,
       2.8, 3. ])

In [ ]:
df["Delivery_person_Ratings"].isna().sum()

np.int64(0)

In [ ]:
df["Delivery_person_Ratings"].dtype

dtype('float64')

In [ ]:
df["Delivery_person_Ratings"].min()

1.0

In [ ]:
df["Delivery_person_Ratings"].max()

6.0

In [ ]:
df["Delivery_person_Ratings"].value_counts()

Delivery_person_Ratings
4.6    1921
4.8    1600
4.7    1549
4.9    1539
5.0     830
4.5     722
4.4     349
4.1     333
4.2     311
4.3     298
4.0     243
3.5      61
3.8      52
3.7      44
3.6      43
3.9      38
3.1      10
6.0      10
3.2       7
2.6       6
2.7       6
2.5       6
3.3       6
3.4       5
1.0       5
2.9       3
2.8       2
3.0       1
Name: count, dtype: int64

Since rating is on the scale of 1-5 , and 10 persons have rating of 6 so now handling them with average rating value.

In [ ]:
avg_rating = df.loc[df["Delivery_person_Ratings"] <= 5, "Delivery_person_Ratings"].mean()

In [ ]:
df.loc[df["Delivery_person_Ratings"] == 6, "Delivery_person_Ratings"] = avg_rating

In [ ]:
df["Delivery_person_Ratings"].describe()

count    10000.000000
mean         4.627998
std          0.320016
min          1.000000
25%          4.500000
50%          4.700000
75%          4.800000
max          5.000000
Name: Delivery_person_Ratings, dtype: float64

Checking temperature , humidity and precipitation columns

In [ ]:
df[["temperature","humidity","precipitation"]].isna().sum()

temperature      5
humidity         5
precipitation    5
dtype: int64

In [ ]:
df["temperature"] = df["temperature"].fillna(df["temperature"].mean())

In [ ]:
df["humidity"] = df["humidity"].fillna(df["humidity"].mean())

In [ ]:
df["precipitation"] = df["precipitation"].fillna(df["precipitation"].mean())

In [ ]:
df[["temperature","humidity","precipitation"]].isna().sum()

temperature      0
humidity         0
precipitation    0
dtype: int64

In [ ]:
df[["temperature","humidity","precipitation"]].dtypes

temperature      float64
humidity         float64
precipitation    float64
dtype: object

In [ ]:
df[["temperature","humidity","precipitation"]].agg(["min","max"])

     temperature  humidity  precipitation
min         6.77      27.0           0.00
max        29.05      94.0           1.46

In [ ]:
df[["temperature","humidity","precipitation"]].describe()

        temperature      humidity  precipitation
count  10000.000000  10000.000000   10000.000000
mean      22.936907     66.164882       0.016233
std        3.378603     15.599037       0.074893
min        6.770000     27.000000       0.000000
25%       20.140000     54.000000       0.000000
50%       22.990000     67.000000       0.000000
75%       25.980000     81.000000       0.000000
max       29.050000     94.000000       1.460000

Distance Column

In [ ]:
df["Distance (km)"].isna().sum()

np.int64(920)

In [ ]:
df[df["Distance (km)"].isna()]

,Traffic_Level,ID,Delivery_person_ID,weather_description,Type_of_order,Type_of_vehicle,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,temperature,humidity,precipitation,Distance (km),TARGET
556,High,B4D6,RANCHIRES13DEL02,clear sky,Drinks,motorcycle,24,4.9,23.374.989,85.335.486,23.424.989,85.385.486,17.84,68.0,0.00,NaN,4.318.333.333
815,High,B473,COIMBRES02DEL03,mist,Drinks,motorcycle,28,4.4,11.022.477,76.995.667,11.112.477,77.085.667,25.12,73.0,0.00,NaN,45.85
2660,High,5802,COIMBRES13DEL02,haze,Meal,motorcycle,30,3.6,11.003.669,76.976.494,11.083.669,77.056.494,25.97,73.0,0.00,NaN,3.273.333.333
2736,Low,4607,INDORES13DEL02,haze,Snack,motorcycle,37,4.9,22.745.049,75.892.471,22.765.049,75.912.471,17.11,77.0,0.00,NaN,2.166.666.667
6681,NaN,2876,RANCHIRES02DEL01,overcast clouds,Snack,scooter,32,3.5,0,0,0.11,0.11,26.27,84.0,0.00,NaN,#VALUE!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7592,NaN,C032,KOLRES08DEL01,haze,Meal,scooter,28,4.7,-2.253.796,88.349.843,2.260.796,88.419.843,28.00,65.0,0.00,NaN,#VALUE!
7593,NaN,D1F1,AURGRES20DEL01,light rain,Snack,electric_scooter,21,4.9,0,0,0.11,0.11,26.41,82.0,0.25,NaN,NaN
7594,NaN,C5A8,BHPRES14DEL02,light rain,Snack,scooter,24,4.8,0,0,0.08,0.08,26.37,82.0,0.27,NaN,NaN
7595,NaN,C7C4,KNPRES08DEL01,light rain,Drinks,motorcycle,22,4.3,0,0,0.04,0.04,26.34,82.0,0.30,NaN,NaN
9324,Very High,802,MUMRES18DEL03,smoke,Meal,motorcycle,37,4.6,191.093,72.825.451,191.993,72.915.451,26.96,57.0,0.00,NaN,7.033.333.333

In [ ]:
(df["Distance (km)"] == 0).sum()

np.int64(0)

In [ ]:
avg_distance = df["Distance (km)"].mean()

In [ ]:
df["Distance (km)"] = df["Distance (km)"].fillna(avg_distance)

In [ ]:
df["Distance (km)"].isna().sum()

np.int64(0)

Target Column

In [ ]:
valid_count = pd.to_numeric(df["TARGET"], errors="coerce").notna().sum()
print(valid_count)

3001

In [ ]:
df["TARGET"] = df["TARGET"].astype(str).str.replace(r"\D", "", regex=True)

In [ ]:
df.loc[df["TARGET"] == "", "TARGET"] = pd.NA

In [ ]:
df["TARGET"] = df["TARGET"].str[:4]

In [ ]:
df["TARGET"] = pd.to_numeric(df["TARGET"], errors="coerce") / 100

In [ ]:
df["TARGET"].describe()

count    9040.000000
mean       32.437977
std        19.805813
min         0.080000
25%        18.050000
50%        32.470000
75%        45.487500
max        99.850000
Name: TARGET, dtype: float64

In [ ]:
df["TARGET"].head(20)

0     43.45
1     38.16
2     36.36
3     49.45
4     52.48
5     34.61
6     44.16
7     54.38
8     47.46
9     47.28
10    46.25
11    40.61
12    44.18
13    46.45
14    50.35
15    49.71
16     4.23
17    45.48
18    45.58
19    36.36
Name: TARGET, dtype: float64

In [ ]:
df["TARGET"].isna().sum()

np.int64(960)

In [ ]:
avg_time = df["TARGET"].mean()

In [ ]:
df["TARGET"] = df["TARGET"].fillna(avg_time)

In [ ]:
df["TARGET"].isna().sum()

np.int64(0)

In [ ]:
df.isna().sum()

Traffic_Level                  915
ID                               0
Delivery_person_ID               0
weather_description              5
Type_of_order                    0
Type_of_vehicle                  0
Delivery_person_Age              0
Delivery_person_Ratings          0
Restaurant_latitude              0
Restaurant_longitude             0
Delivery_location_latitude       0
Delivery_location_longitude      0
temperature                      0
humidity                         0
precipitation                    0
Distance (km)                    0
TARGET                           0
dtype: int64

In [ ]:
df.to_csv("cleaned_food_delivery_data.csv", index=False)

In [ ]:
from google.colab import files
files.download("cleaned_food_delivery_data.csv")